version: '3'

services:
  web:
    build: ./app
    volumes:
      - ./app:/app  # Montar el código de la aplicación desde el host
      - ./logs:/logs  # Montar el directorio de logs para escribir en el host
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  # Establecer variable de entorno para el modo de desarrollo
      - REDIS_HOST=redis  # Establecer el nombre del servicio Redis
      - REDIS_PORT=6379  # Establecer el puerto del servicio Redis
    command: sh -c "pip install -r requirements.txt && python app.py"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
