#version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=example
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    volumes:
      - db_data:/var/lib/postgresql/data

  phppgadmin:
    image: dockage/phppgadmin
    environment:
      - 'PGA_HOST=db'
      - 'PGA_PORT=5432'
      - 'PGA_DEFAULTDB=postgres'
      - 'PGA_DEFAULTDBUSER=postgres'
      - 'PGA_DEFAULTDBPASS=example'
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
