#version: '3.8'

services:
  web:
    build: ./app
    env_file:
      - env_test1.env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 10 && python app.py"]  

  db:
    image: postgres:13-alpine
    env_file:
      - env_test1.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phppgadmin:
    image: dockage/phppgadmin
    env_file:
      - env_test1.env
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
