services:
  web:
    build: ./app
    # Cargar el fichero con las variables de entorno
    env_file:
      - env_test1.env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 10 && python app.py"]  

  db:
    image: postgres:13-alpine
    # Cargar el fichero con las variables de entorno
    env_file:
      - env_test1.env
    volumes:
      - db_data:/var/lib/postgresql/data
      # Configuracion inicial de la base de dattos 
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./generate_init_sql.sh:/docker-entrypoint-initdb.d/generate_init_sql.sh
    entrypoint: ["/bin/sh", "-c", "chmod +x /docker-entrypoint-initdb.d/generate_init_sql.sh && /docker-entrypoint-initdb.d/generate_init_sql.sh && docker-entrypoint.sh postgres"] 

  phppgadmin:
    image: dockage/phppgadmin
    # Cargar el fichero con las variables de entorno
    env_file:
      - env_test1.env
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
