services:
  web:
    #build: ./app
    image: bryyyan/practica_contendores:appweb_v1
    # Cargar el fichero con las variables de entorno
    env_file:
      - ./data/env_test1.env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    # Espera 10 segundos antes de lanzar la creacion de la DDBB  
    entrypoint: ["sh", "-c", "sleep 10 && python app.py"]  

  db:
    #build: ./data
    image: bryyyan/practica_contendores:appdata_v1
    restart: always
    volumes:
    # Para asegurar persistencia
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    # Cargar el fichero con las variables de entorno
    env_file:
      - ./data/env_test1.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
volumes:
  db_data:
