server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
#
#- job_name: system
#  static_configs:
#  - targets:
#      - "localhost"
#    labels:
#      job: varlogs
#      __path__: /var/log/*log
# Faltaba apuntar a los log de Flask y PostgreSQL y recolectar los logs
  - job_name: flask_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask
          __path__: /app/logs/*.log  # Ruta donde están los logs de la aplicación Flask
          
  - job_name: postgres_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: /var/lib/postgresql/data/log/*.log  # Ruta donde están los logs de Postgres