version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
